apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: production
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.2
        ports:
         - containerPort: 80
      - name: jboss
        image: jboss/wildfly:11.0.0.Final
        ports:
         - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: production
  labels:
    app: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30020
  type: NodePort
  selector:
    app: nginx-pod
