# https://kubernetes.io/docs/concepts/services-networking/service/
# https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-deployment-php
  labels:
    app: lamp-deployment-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-pod-differents-pods
  template:
    metadata:
      name: lamp-pod-php
      labels:
        app: lamp-pod-differents-pods
    spec:
      containers:
      - name: php
        image: svendocker/php-mysql
        ports:
         - containerPort: 80
        volumeMounts:
         - mountPath: /var/www/html/
           name: php-source
      volumes:
       - name: php-source
         hostPath:
           path: /examples/lamp-differents-pods/php-code/
           type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-deployment-mysql
  labels:
    app: lamp-deployment-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-pod-differents-pods
  template:
    metadata:
      name: lamp-pod-mysql
      labels:
        app: lamp-pod-differents-pods
    spec:
      containers:
      - name: mysql
        image: mysql:5.5
        ports:
         - containerPort: 3306
        volumeMounts:
         - mountPath: /docker-entrypoint-initdb.d
           name: mysql-init
        env:
         - name: MYSQL_DATABASE
           value: "foo_database"
         - name: MYSQL_USER
           value: "foo_user"
         - name: MYSQL_PASSWORD
           value: "foo_password"
         - name: MYSQL_RANDOM_ROOT_PASSWORD
           value: "true"
      volumes:
       - name: mysql-init
         hostPath:
           path: /examples/lamp/mysql-scripts/
           type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: lamp-service-differents-pods
  labels:
    app: lamp-service-differents-pods
spec:
  ports:
  - name: php-port
    port: 80
    protocol: TCP
    nodePort: 30081
  - name: mysql-port
    port: 3306
    protocol: TCP
    nodePort: 32307
  clusterIP: 10.96.0.2
  type: NodePort
  selector:
    app: lamp-pod-differents-pods
