  
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

   config.vm.box_check_update = "false"
   config.vm.hostname = "jessie-master"
   config.vm.synced_folder "install", "/install"
   config.vm.synced_folder "examples", "/examples"

   config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = 2048
     end

   config.vm.provision "shell", inline: <<-SHELL

     #update kernel
     echo "deb http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list.d/sources.list
     echo "deb-src http://http.debian.net/debian jessie-backports main" >> /etc/apt/sources.list.d/sources.list
     sudo apt-get update
     sudo apt-get install -y -t jessie-backports linux-image-4.9.0-0.bpo.6-amd64
     sudo apt-get clean
     sed -i '/GRUB_CMDLINE_LINUX/d' /etc/default/grub
     echo "GRUB_CMDLINE_LINUX=\"cgroup_enable=memory\"" >> /etc/default/grub
     echo "export KUBECONFIG=$HOME/.kube/config" >> /home/vagrant/.profile
    
     #root command
     #sudo su && echo 1 > /proc/sys/vm/drop_caches
  SHELL

end
