  
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

   config.vm.box_check_update = "false"
   config.vm.hostname = "jessie-master"
   config.vm.synced_folder "install", "/install"
   config.vm.synced_folder "examples", "/examples"

   config.vm.network "public_network"

   config.vm.provider "virtualbox" do |vb|
       vb.gui = false
       vb.memory = 2028
     end

   config.vm.provision "shell", inline: <<-SHELL

     #update kernel
     echo 'Acquire::Check-Valid-Until false;' > /etc/apt/apt.conf.d/archive
     echo 'deb http://snapshot.debian.org/archive/debian/20160529T223338Z/ jessie-backports main contrib non-free' > /etc/apt/sources.list.d/debian-snapshot.list
     apt-get update
     apt-get -y install linux-image-4.9-amd64
     sudo apt-get clean
     sed -i '/GRUB_CMDLINE_LINUX/d' /etc/default/grub
     echo "GRUB_CMDLINE_LINUX=\"cgroup_enable=memory\"" >> /etc/default/grub
     echo "export KUBECONFIG=$HOME/.kube/config" >> /home/vagrant/.profile
    
     #root command
     #sudo su && echo 1 > /proc/sys/vm/drop_caches
  SHELL

end
